# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Timely Matter
subtitle: >
  Experiments on the entanglements of technology,<br/>
  time and the present moment
email: mail@davidbeermann.com
description: > # this means to ignore newlines until "baseurl:"
  ...
baseurl: "/timely-matter" # the subpath of your site, e.g. /blog
url: "https://davidbeermann.github.io" # the base hostname & protocol for your site

google_fonts: https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,400i,700,700i

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.md"
  - "package.json"
  - "node_modules"
  - "scripts"
  - "npm-debug.log"
  - "gulpfile.js"
